services:
  dockme:
    container_name: dockme
    image: ghcr.io/fernandeusto/dockme:latest
    restart: always
    
    environment:
      HOSTNAME: "ServidorRemoto" #opcional, si no se especifica se usará el hostname del contenedor
      CHECK_TIMES: "15:00" #opcional, formato HH:MM, hora a la que se realizará el check de stacks, si no se especifica se hará cada 24h

    #opcional para recibir notificaciones por telegram, se deben configurar las siguientes dos variables:
      TELEGRAM_TOKEN: "123456:ABC-DEF..."
      TELEGRAM_CHATID: "987654321"
    
    ports:
      - "5041:8080"   # Puerto para la interfaz web
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # para gestionar los docker del host
      - ./dockme-data:/app/data                   # para persistir configuraciones, iconos, etc.
      - ./stacks:/opt/stacks:rw                   # ubicacion de archivos compose.yml de cada stack