services:
  dockme:
    container_name: dockme
    image: ghcr.io/fernandeusto/dockme:latest
    restart: always
    
    environment:
      HOSTNAME: "Dockme-Remoto" # ⚠️ Obligatorio, asignar el nombre con el que identificarlo
      CENTRAL_URL: "192.168.1.200:5041"  # IP:Puerto del servidor central accesible desde el remoto
      AGENT_URL: "192.168.1.100:5041"  # IP:Puerto del servidor remoto accesible desde el central

    ports:
      - "5041:8080"  # Puerto debe coincidir con AGENT_URL
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # para gestionar los docker del host
      - ./dockme-data:/app/data                   # para persistir configuraciones, iconos, etc.
      - ./stacks:/opt/stacks:rw                   # ubicacion de archivos compose.yml de cada stack