services:
  dockme:
    container_name: dockme
    image: ghcr.io/fernandeusto/dockme:latest
    restart: always
    
    environment:
      HOSTNAME: "ServidorRemoto" #opcional, si no se especifica se usará el hostname del contenedor
      CHECK_TIMES: "15:00" #opcional, formato HH:MM, hora a la que se realizará el check de stacks, si no se especifica se hará cada 24h

    #opcional para recibir notificaciones por telegram, se deben configurar las siguientes dos variables:
      TELEGRAM_TOKEN: "123456:ABC-DEF..."
      TELEGRAM_CHATID: "987654321"

    #para usar un servidor remoto, se deben configurar las siguientes variables obligatoriamente:
      ENDPOINT: "192.168.1.200:5041"  # IP:Puerto para acceder al servidor remoto desde el central
      WEBHOOK_URL: "http://192.168.1.100:5041"  # URL del servidor central al que se enviarán updates, métricas,...

    ports:
      - "5041:8080"  # Puerto debe coincidir con ENDPOINT
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # para gestionar los docker del host
      - ./dockme-data:/app/data                   # para persistir configuraciones, iconos, etc.
      - ./stacks:/opt/stacks:rw                   # ubicacion de archivos compose.yml de cada stack